Feat/resend
nova-peru/nova.github.io pull request #14
Opened 2024-01-21 00:46 UTC by enrique-holguin

Feature: Resend and Toast Notifications for Contact Form
Changes:

Implemented message resend capability in the contact form.
Added toast notifications for user feedback.
Objective:
Enhances user experience by allowing message resending and providing real-time feedback through toast notifications in the contact form.

Testing:

Visit the contact form.
Submit a message.
Test the resend feature.
Observe toast notifications for instant feedback.

2024-01-26 00:27 UTC, zendostrike requested changes

2024-01-26 00:27 UTC, zendostrike commented on components/Contact/index.tsx
> +    const formData = new FormData(e.currentTarget)
creo que aqui puedes simplemente llamar a `e.nameDelInput.value` para evitar crear un FormData.

2024-01-26 00:27 UTC, zendostrike commented on app/api/send/route.tsx
> +  const companyName = "Nova"
Este CompanyName colocalo en una variable de entorno. Cosa que queda configurable desde un PaaS sin necesidad de tocar el codigo

2024-01-26 00:27 UTC, zendostrike commented on app/api/send/route.tsx
> +export const dynamic = "force-static";
esta constante se usa? si no eliminala

2024-01-26 00:27 UTC, zendostrike commented on schemas/form.schema.ts
> +export const checkoutFormSchema = z.object({
Refactorizar esta variable con el nombre de contactUsFormSchema

2024-01-26 00:27 UTC, zendostrike commented on components/Contact/index.tsx
> +                    <button disabled={status === "loading" ? true : false} className="w-60 rounded-md bg-primary py-4 text-base font-medium text-white transition duration-300 ease-in-out hover:bg-opa
en lugar del ternario solo hacer `status === "loading"`. Retornara un boolean de todas formas.

2024-01-26 00:27 UTC, zendostrike commented on components/Contact/index.tsx
> +    const successMsg = "Mensaje enviado ✔"
constantes no necesarias, no se repiten en el codigo, seria mejor solo colocar el string pelao :D

2024-01-26 00:27 UTC, zendostrike commented on components/Contact/index.tsx
> +    const errorMsg = "Error al enviar mensaje ❌"
esta tambien

2024-01-26 00:27 UTC, zendostrike commented on components/Contact/index.tsx
> +      const succesCode = 200
En este caso como sabemos que se va a volver a repetir esta constante seria bueno sacarlo a una carpeta de constantes generales.  y dentro crear un archivo http, y exportar una constante o enum, HttpStatusCode y dentro colocar los mas usados: OK: 200, INTERNAL_SERVER_ERROR: 500, NOT_FOUND: 404, BAD_REQUEST: 400, 
 etc

2024-01-26 00:27 UTC, zendostrike commented on components/Contact/index.tsx
> +  const [status, setStatus] = useState<"loading" | "success" | "error" | "idle">("idle")
crea un type encima del Component, que se llame FormStatus y le pones: "loading" | "success" | "error" | "idle".

`type FormStatus = "loading" | "success" | "error" | "idle"`

2024-01-26 00:27 UTC, zendostrike commented on components/Carousel/index.tsx
> +export default Carousel
devuelve el componente en un `export default React.memo(Carousel)`

2024-01-26 00:35 UTC, zendostrike commented on app/api/send/route.tsx
> +  const companyName = "Nova"
Agregar la env de company en el footer

2024-01-29 19:47 UTC, enrique-holguin commented on components/Contact/index.tsx
> +    const formData = new FormData(e.currentTarget)
No se puede hacer directamente porque la propiedad name ya es un valor existente del tipo React.FormEvent<HTMLFormElement>
Por lo que al intentar transformarla arroja un error .

![value_name_error](https://github.com/nova-peru/nova.github.io/assets/116053539/89004aa4-7a27-4f50-9af0-19f4d0f3fc9c)

La forma de hacer la conversión sería cambiar el tipo de e.currentTarget.name a unknown y luego a {value:string} para así poder extraer el valor

![value_name](https://github.com/nova-peru/nova.github.io/assets/116053539/073b8d6d-5eb2-4006-97cf-9e5440490905)

2024-01-30 03:07 UTC, merged