Feat/bot videos
nova-peru/nova.github.io pull request #43
Opened 2024-03-26 20:34 UTC by enrique-holguin

add VideoItem component ✔

2024-03-26 20:40 UTC, zendostrike requested changes

2024-03-26 20:40 UTC, zendostrike commented on components/Video/VideoItem.tsx
> +
aca podrias hacer:

```
const handleToggleOpen = useCallback(() => {
  setOpen(isOpen => !isOpen);
}, []);
```

y llamarlo tanto en donde se abre el modal como donde se cierra.

```
<button onClick={handleToggleOpen} />
```

2024-03-26 20:40 UTC, zendostrike commented on components/Video/index.tsx
> +          {videos.map(video => <VideoItem key={video.id} id={video.id} image={video.image}></VideoItem>)}
podrías usar un useMemo para no rerendizar esta lista de videos:

```
const renderVideos = useMemo(() => videos.map(...), [videos]);
```

2024-03-26 21:08 UTC, enrique-holguin commented on components/Video/VideoItem.tsx
> +
Cuando se usa de esa manera, al abrir el modal y presionar la tecla ESC, el modal no se cierra, si no que vuelve a refrescar el vídeo, pero presionando en el ícono de cierre (X), el vídeo si se cierra .

```ts
const VideoItem = ({ id, image }:VideoItemProps) => {
  const [isOpen, setOpen] = useState(false);

  const handleToggleOpen = useCallback(() => {
    setOpen(isOpen => !isOpen);
  },[])

  return (
    <div className="w-48 h-full">
      <div className="wow fadeInUp mx-auto max-w-[770px] overflow-hidden rounded-md" data-wow-delay=".15s">
        <div className="relative aspect-[9/20] items-center justify-center">
          <Image data-cy="video-image" src={image} alt="video image" layout="fill" objectFit="contain" />
          <div className="absolute top-0 right-0 flex h-full w-full items-center justify-center">
            <button
              onClick={handleToggleOpen}
              className="flex h-[60px] w-[60px] items-center justify-center rounded-full bg-white bg-opacity-75 text-primary transition hover:bg-opacity-100"
            >
              <svg width="16" height="18" viewBox="0 0 16 18" className="fill-current">
                <path d="M15.5 8.13397C16.1667 8.51888 16.1667 9.48112 15.5 9.86602L2 17.6603C1.33333 18.0452 0.499999 17.564 0.499999 16.7942L0.5 1.20577C0.5 0.43597 1.33333 -0.0451549 2 0.339745L15.5 8.13397Z" />
              </svg>
            </button>
          </div>
        </div>
      </div>
      <ModalVideo
        channel="youtube"
        autoplay={true}
        start={true}
        isOpen={isOpen}
        videoId={id}
        onClose={handleToggleOpen}
      />
    </div>
  );
};
```

2024-03-26 21:10 UTC, enrique-holguin commented on components/Video/index.tsx
> +          {videos.map(video => <VideoItem key={video.id} id={video.id} image={video.image}></VideoItem>)}
Se añadió de esta forma :
```tsx
<div className="-mx-4 flex flex-row space-x-12 justify-center">
          {useMemo(() => 
          videos.map(video => 
          <VideoItem key={video.id} id={video.id} image={video.image}></VideoItem>),
          [])}
        </div>
```

2024-03-27 14:49 UTC, zendostrike commented on components/Video/index.tsx
> +          {videos.map(video => <VideoItem key={video.id} id={video.id} image={video.image}></VideoItem>)}
no, porfa no usar directamente hooks en el jsx.

2024-03-27 14:51 UTC, zendostrike commented on components/Video/VideoItem.tsx
> +
cambia el nombre de la variable dentro del setOpen
```
setOpen(val => !val)
```

2024-03-27 14:52 UTC, zendostrike commented on components/Video/index.tsx
> +          {videos.map(video => <VideoItem key={video.id} id={video.id} image={video.image}></VideoItem>)}
mientras menos codigo en el jsx mejor, por eso sacar lo a una funcion que se encargue de ello y el jsx queda mas legible.

2024-03-27 14:56 UTC, enrique-holguin commented on components/Video/VideoItem.tsx
> +
Sigue con el mismo comportamiento, al presionar ESC este no cierra el vídeo, se refresca.
```tsx
const handleToggleOpen = useCallback(() => {
    setOpen(val => !val);
  },[])
```

2024-04-02 18:04 UTC, merged